-- 0016_users_email_partial_unique.sql
--
-- Make `users.email` uniqueness apply ONLY to live (non-deleted) users.
--
-- Why:
--   The current unconditional UNIQUE (email) means once a user is
--   soft-deleted, that address is occupied forever — re-signup with
--   the same email hits a UNIQUE violation. App Store guideline
--   5.1.1(v) reviewers routinely test "delete account → re-sign-up"
--   and we need that flow to work.
--
--   `DELETE /v1/users/me` already scrambles the email on its way
--   out, so users who delete from inside the app are unaffected.
--   But the `user.deleted` Clerk webhook path (admin deletes from
--   the Clerk dashboard, or via Clerk's API) does NOT scramble —
--   so the bug exists for that path. The partial index fixes both
--   uniformly without coupling the schema to a particular delete
--   path's behavior.
--
-- Safety:
--   Pure schema change. NO row deleted, NO column dropped, NO
--   data altered. The destructive-pattern guard in
--   `packages/db/scripts/reconcile-migrations.ts` checks for
--   TRUNCATE / DELETE FROM / DROP TABLE — none present here.
--   `DROP CONSTRAINT` on a UNIQUE constraint just removes the
--   constraint and its backing index; the column data is untouched.
--
-- Order:
--   We CREATE the new partial index FIRST and DROP the old
--   constraint SECOND. Both run inside the migration's
--   transaction, so live-user uniqueness is enforced continuously
--   throughout the migration.

-- ── Step 1: partial unique index covering only live rows ─────────
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_active_unique_idx"
  ON "users" ("email")
  WHERE "is_deleted" = false;
--> statement-breakpoint

-- ── Step 2: drop the unconditional UNIQUE constraint ─────────────
-- The original constraint was generated by Drizzle's `.unique()`
-- declaration on the email column. Dropping the constraint also
-- drops the matching `users_email_unique` btree index (Postgres
-- creates one implicitly to enforce a UNIQUE constraint).
ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_email_unique";
