/**
 * Seed the plan catalogue — four tiers, monthly and yearly.
 *
 * ─── HOW THE CREDIT AMOUNTS WERE DERIVED ────────────────────────────
 *
 * House rule (verified against every priced model): a credit costs us
 * `provider_USD / 300`, i.e. $0.0033, and carries a nominal $0.01 face
 * value. So an allowance of N credits costs us at most `N * 0.0033` if
 * the customer burns every one of them.
 *
 *   tier      $/mo   credits   $/credit   cost @100%   margin @100%
 *   basic       19     2,000    0.0095       $6.67         65%
 *   creator     39     4,500    0.0087      $15.00         62%
 *   pro         75     9,000    0.0083      $30.00         60%
 *   ultimate    99    12,500    0.0079      $41.67         58%
 *
 * Two properties this is built on:
 *   - `$/credit` FALLS with every tier, so upgrading is always better
 *     value. Every comparable tool does this (Higgsfield $0.070 → $0.043,
 *     Runway $0.024 → $0.010) and customers expect it.
 *   - Margin holds above 58% even at 100% utilisation, which essentially
 *     never happens. Real margin is higher; this is the floor, not the
 *     expectation.
 *
 * For scale, Basic buys 50 Nano Banana Pro images or 8 Seedance 2.0
 * videos; Ultimate buys 312 images or 54 videos. That lands in the same
 * territory as Higgsfield's equivalent plans.
 *
 * ─── YEARLY ─────────────────────────────────────────────────────────
 *
 * Two months free (pay for 10, get 12) — 16.7% off, and far easier to
 * explain than a percentage.
 *
 * ⚠️ A yearly plan grants the MONTHLY allowance every 30 days, NOT twelve
 * months' worth up front. Granting 150,000 credits to an annual Ultimate
 * subscriber on day one invites burning the lot in month one, which turns
 * a comfortable margin into a very expensive month. Higgsfield does the
 * same ("on annual plans every 30 days"). The stores and Stripe only send
 * a renewal event once a year, so `refresh-subscription-credits` handles
 * the intervening months.
 *
 * ─── PRODUCT IDs ARE DELIBERATELY NOT SEEDED ────────────────────────
 *
 * `plan_products` rows are created when the real products exist in
 * Stripe, App Store Connect and Play Console — never before. Seeding
 * plausible-looking placeholders is exactly what left production with
 * `weekly` / `monthly` / `Pack-ultimate`, none of which any storefront
 * has ever heard of; a real purchase would look up the id, find nothing,
 * and grant nothing.
 *
 * The intended convention, for when they are created:
 *   Apple   ai.clickefy.app.<tier>.<interval>   (dots allowed)
 *   Google  <tier>_<interval>                   (lowercase + underscore)
 *   Stripe  price_… (generated by Stripe)
 *
 * Usage:
 *   DATABASE_URL=... pnpm tsx scripts/seed-plans-catalog.ts
 *   DATABASE_URL=... pnpm tsx scripts/seed-plans-catalog.ts --apply
 */

import { neon } from '@neondatabase/serverless';

const url = process.env.DATABASE_URL;
if (!url) {
  console.error('DATABASE_URL is not set');
  process.exit(1);
}
const apply = process.argv.includes('--apply');
const sql = neon(url);
const q = <T = Record<string, unknown>>(s: string) =>
  sql(Object.assign([s], { raw: [s] }) as unknown as TemplateStringsArray) as unknown as Promise<T[]>;

/** Provider cost carried by one credit — the basis for the margin column. */
const COST_PER_CREDIT = 1 / 300;

interface TierDef {
  tier: string;
  label: string;
  monthlyUsd: number;
  /** Credits granted EVERY 30 DAYS, on monthly and yearly alike. */
  creditsPerPeriod: number;
  order: number;
}

const TIERS: TierDef[] = [
  { tier: 'basic', label: 'Basic', monthlyUsd: 19, creditsPerPeriod: 2_000, order: 1 },
  { tier: 'creator', label: 'Creator', monthlyUsd: 39, creditsPerPeriod: 4_500, order: 2 },
  { tier: 'pro', label: 'Pro', monthlyUsd: 75, creditsPerPeriod: 9_000, order: 3 },
  { tier: 'ultimate', label: 'Ultimate', monthlyUsd: 99, creditsPerPeriod: 12_500, order: 4 },
];

/** Pay for ten months, get twelve. */
const YEARLY_MONTHS_CHARGED = 10;

async function main() {
  const host = new URL(url!.replace('postgresql://', 'https://')).hostname;
  console.log(`Target: ${host}`);
  console.log(apply ? 'Mode:   APPLY\n' : 'Mode:   DRY RUN (pass --apply to write)\n');

  console.log(
    `${'tier'.padEnd(10)}${'interval'.padEnd(9)}${'price'.padStart(8)}${'credits'.padStart(9)}` +
      `${'$/credit'.padStart(10)}${'margin*'.padStart(9)}   action`,
  );
  console.log('─'.repeat(78));

  let created = 0;
  let updated = 0;

  for (const t of TIERS) {
    for (const interval of ['month', 'year'] as const) {
      const price = interval === 'month' ? t.monthlyUsd : t.monthlyUsd * YEARLY_MONTHS_CHARGED;
      const displayName = interval === 'month' ? t.label : `${t.label} (yearly)`;
      // Credits are per 30-day period in BOTH cases — see the header.
      const credits = t.creditsPerPeriod;
      const perCreditMonthly = t.monthlyUsd / credits;
      const margin = ((t.monthlyUsd - credits * COST_PER_CREDIT) / t.monthlyUsd) * 100;

      const existing = await q<{ id: string; credits_per_period: number }>(
        `SELECT id, credits_per_period FROM plans
         WHERE tier = '${t.tier}' AND "interval" = '${interval}'`,
      );

      let action: string;
      if (existing.length === 0) {
        action = 'create';
        created += 1;
      } else if (Number(existing[0]!.credits_per_period) !== credits) {
        action = `update credits ${existing[0]!.credits_per_period} → ${credits}`;
        updated += 1;
      } else {
        action = 'unchanged';
      }

      console.log(
        `${t.tier.padEnd(10)}${interval.padEnd(9)}${('$' + price).padStart(8)}${credits.toLocaleString().padStart(9)}` +
          `${perCreditMonthly.toFixed(4).padStart(10)}${(margin.toFixed(0) + '%').padStart(9)}   ${action}`,
      );

      if (!apply || action === 'unchanged') continue;

      await q(`
        INSERT INTO plans (tier, "interval", credits_per_period, display_name, display_order, is_active, notes)
        VALUES ('${t.tier}', '${interval}', ${credits}, '${displayName.replace(/'/g, "''")}',
                ${t.order * 10 + (interval === 'year' ? 1 : 0)}, true,
                'Indicative web price $${price}. Credits granted every 30 days on both intervals.')
        ON CONFLICT (tier, "interval") DO UPDATE
          SET credits_per_period = EXCLUDED.credits_per_period,
              display_name       = EXCLUDED.display_name,
              display_order      = EXCLUDED.display_order,
              notes              = EXCLUDED.notes,
              updated_at         = now()`);
    }
  }

  console.log('\n* margin if the customer burns 100% of their allowance — the floor, not the expectation.');

  // The migrated `pro` rows from 0031 carried the OLD credit amounts and
  // display names; the upsert above corrects them in place rather than
  // leaving two competing definitions of the same plan.
  if (!apply) {
    console.log(`\nWould create ${created} plan(s), update ${updated}. Re-run with --apply.`);
    return;
  }

  const all = await q<{ tier: string; interval: string; credits_per_period: number; is_active: boolean }>(
    `SELECT tier, "interval", credits_per_period, is_active FROM plans ORDER BY display_order`,
  );
  console.log(`\n✔ ${all.length} plan(s) in the catalogue:`);
  for (const p of all) {
    console.log(`   ${p.tier}/${p.interval} — ${Number(p.credits_per_period).toLocaleString()}cr per 30 days, active=${p.is_active}`);
  }

  const orphaned = await q<{ n: number }>(`
    SELECT COUNT(*)::int n FROM plans p
    WHERE p.is_active AND NOT EXISTS (SELECT 1 FROM plan_products pp WHERE pp.plan_id = p.id)`);
  if (orphaned[0]!.n > 0) {
    console.log(
      `\n  ${orphaned[0]!.n} active plan(s) have no storefront products yet — expected until` +
        `\n  Stripe prices and store products are created. Nothing is sellable until then,` +
        `\n  which is the safe state: a webhook can only grant what it can look up.`,
    );
  }
}

main().catch((err) => {
  console.error('\nFailed:', err);
  process.exit(1);
});
