import { GoogleGenAI } from '@google/genai';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

const ROLE_LABELS: Record<string, string> = {
  style: 'STYLE REFERENCE',
  composition: 'COMPOSITION REFERENCE',
  lighting: 'LIGHTING REFERENCE',
  scene: 'SCENE REFERENCE',
  example: 'EXAMPLE REFERENCE',
};

export interface GeminiReferenceImage {
  base64: string;
  mimeType: string;
  role: string;
  label: string;
}

export interface GeminiGenerateRequest {
  model: string;
  prompt: string;
  referenceImages?: GeminiReferenceImage[];
  inputImages?: { base64: string; mimeType: string; label?: string }[];
  aspectRatio?: string;
  numberOfOutputs?: number;
}

export interface GeminiGenerateResult {
  images: { base64: string; mimeType: string }[];
}

type ContentPart =
  | { text: string }
  | { inlineData: { mimeType: string; data: string } };

/**
 * Build a labeled multimodal contents array.
 *
 * Order:
 *  1. Reference images (admin-provided) — each preceded by a role label
 *  2. User input images — each preceded by a subject label
 *  3. The generation prompt
 *
 * This structure prevents Gemini from confusing reference material
 * with the actual subject the user wants featured.
 */
function buildContents(request: GeminiGenerateRequest): ContentPart[] {
  const contents: ContentPart[] = [];

  if (request.referenceImages?.length) {
    for (const ref of request.referenceImages) {
      const roleLabel = ROLE_LABELS[ref.role] || 'REFERENCE';
      const desc = ref.label ? ` — ${ref.label}` : '';
      contents.push({
        text: `[${roleLabel}${desc}. Use this ONLY as inspiration for the generated image. Do NOT reproduce or copy this image]:`,
      });
      contents.push({
        inlineData: { mimeType: ref.mimeType, data: ref.base64 },
      });
    }
  }

  if (request.inputImages?.length) {
    for (const img of request.inputImages) {
      const label = img.label || 'Product/Subject';
      contents.push({
        text: `[USER INPUT — ${label}. This is the main subject that MUST appear prominently in the generated result]:`,
      });
      contents.push({
        inlineData: { mimeType: img.mimeType, data: img.base64 },
      });
    }
  }

  contents.push({ text: request.prompt });

  return contents;
}

/**
 * Generate images using Gemini's native image generation models.
 * Supports text-to-image, image-to-image, and reference-guided generation.
 *
 * Compatible models:
 *  - gemini-2.5-flash-image (Nano Banana — fast, high-volume)
 *  - gemini-3.1-flash-image-preview (Nano Banana 2 — latest)
 *  - gemini-3-pro-image-preview (Nano Banana Pro — highest quality)
 */
export async function generateWithGemini(
  request: GeminiGenerateRequest
): Promise<GeminiGenerateResult> {
  const contents = buildContents(request);

  const response = await ai.models.generateContent({
    model: request.model,
    contents,
  });

  const images: { base64: string; mimeType: string }[] = [];

  if (response.candidates) {
    for (const candidate of response.candidates) {
      if (candidate.content?.parts) {
        for (const part of candidate.content.parts) {
          if (part.inlineData?.data && part.inlineData?.mimeType?.startsWith('image/')) {
            images.push({
              base64: part.inlineData.data,
              mimeType: part.inlineData.mimeType,
            });
          }
        }
      }
    }
  }

  if (images.length === 0) {
    throw new Error('No images generated. The model may have filtered the output.');
  }

  return { images };
}

/**
 * Generate images using Imagen 4 (text-to-image only, no input images).
 *
 * Compatible models:
 *  - imagen-4.0-generate-001 (standard)
 *  - imagen-4.0-fast-generate-001 (fast)
 *  - imagen-4.0-ultra-generate-001 (ultra quality)
 */
export async function generateWithImagen(
  request: GeminiGenerateRequest
): Promise<GeminiGenerateResult> {
  const response = await ai.models.generateImages({
    model: request.model,
    prompt: request.prompt,
    config: {
      numberOfImages: request.numberOfOutputs || 1,
      aspectRatio: request.aspectRatio as '1:1' | '3:4' | '4:3' | '9:16' | '16:9' | undefined,
    },
  });

  const images: { base64: string; mimeType: string }[] = [];

  if (response.generatedImages) {
    for (const generated of response.generatedImages) {
      if (generated.image?.imageBytes) {
        images.push({
          base64: generated.image.imageBytes,
          mimeType: 'image/png',
        });
      }
    }
  }

  if (images.length === 0) {
    throw new Error('No images generated by Imagen.');
  }

  return { images };
}
